import type { Metadata } from "next"
import "./globals.css"
import { Anton } from "next/font/google"

const anton = Anton({
  subsets: ["latin"],
  weight: "400",
})

export const metadata: Metadata = {
  title: "My Website",
  description: "Generated by Next.js",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={anton.className}>{children}</body>
    </html>
  )
}

